/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_soma_JniSppourtTestActivity */

#ifndef _Included_com_android_soma_JniSppourtTestActivity
#define _Included_com_android_soma_JniSppourtTestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_soma_JniSppourtTestActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_soma_JniSppourtTestActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
